# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kmpsample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '13.6'

  # Pods for kmpsample

  target 'kmpsampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kmpsampleUITests' do
    # Pods for testing
  end
   
  pod 'kmp_sample', :path => '../lib'

end
